package main

import "fmt"

func main() {
	s := "Escape"
	fmt.Println(s)
}

/*
bogon:case3 luxuefeng$ go build -gcflags=-m
# study/mem-leak/case3
./check.go:7:13: inlining call to fmt.Println
./check.go:7:13: s escapes to heap
./check.go:7:13: []interface {} literal does not escape
<autogenerated>:1: .this does not escape
*/
