package main

type AutoGenerated struct {
	LocatedBlocks LocatedBlocks `json:"LocatedBlocks"`
}
type Block struct {
	BlockID         int    `json:"blockId"`
	BlockPoolID     string `json:"blockPoolId"`
	GenerationStamp int64  `json:"generationStamp"`
	NumBytes        int    `json:"numBytes"`
}
type BlockToken struct {
	URLString string `json:"urlString"`
}
type Locations struct {
	AdminState               string `json:"adminState"`
	BlockPoolUsed            int64  `json:"blockPoolUsed"`
	CacheCapacity            int    `json:"cacheCapacity"`
	CacheUsed                int    `json:"cacheUsed"`
	Capacity                 int64  `json:"capacity"`
	DfsUsed                  int64  `json:"dfsUsed"`
	HostName                 string `json:"hostName"`
	InfoPort                 int    `json:"infoPort"`
	InfoSecurePort           int    `json:"infoSecurePort"`
	IPAddr                   string `json:"ipAddr"`
	IpcPort                  int    `json:"ipcPort"`
	LastBlockReportMonotonic int64  `json:"lastBlockReportMonotonic"`
	LastBlockReportTime      int64  `json:"lastBlockReportTime"`
	LastUpdate               int64  `json:"lastUpdate"`
	LastUpdateMonotonic      int64  `json:"lastUpdateMonotonic"`
	Name                     string `json:"name"`
	NetworkLocation          string `json:"networkLocation"`
	Remaining                int64  `json:"remaining"`
	StorageID                string `json:"storageID"`
	XceiverCount             int    `json:"xceiverCount"`
	XferPort                 int    `json:"xferPort"`
}
type LastLocatedBlock struct {
	Block           Block         `json:"block"`
	BlockToken      BlockToken    `json:"blockToken"`
	CachedLocations []interface{} `json:"cachedLocations"`
	IsCorrupt       bool          `json:"isCorrupt"`
	Locations       []Locations   `json:"locations"`
	StartOffset     int           `json:"startOffset"`
	StorageTypes    []string      `json:"storageTypes"`
}
type LocatedBlock struct {
	Block           Block         `json:"block"`
	BlockToken      BlockToken    `json:"blockToken"`
	CachedLocations []interface{} `json:"cachedLocations"`
	IsCorrupt       bool          `json:"isCorrupt"`
	Locations       []Locations   `json:"locations"`
	StartOffset     int           `json:"startOffset"`
	StorageTypes    []string      `json:"storageTypes"`
}
type LocatedBlocks struct {
	FileLength          int              `json:"fileLength"`
	IsLastBlockComplete bool             `json:"isLastBlockComplete"`
	IsUnderConstruction bool             `json:"isUnderConstruction"`
	LastLocatedBlock    LastLocatedBlock `json:"lastLocatedBlock"`
	LocatedBlocks       []LocatedBlock   `json:"locatedBlocks"`
}

//LastLocatedBlock
/*
{
    "LocatedBlocks": {
        "fileLength": 393656398,
        "isLastBlockComplete": true,
        "isUnderConstruction": false,
        "lastLocatedBlock": {
            "block": {
                "blockId": 1122203888,
                "blockPoolId": "BP-2028409268-10.4.1.16-1583828325109",
                "generationStamp": 2377258060,
                "numBytes": 125220942
            },
            "blockToken": {
                "urlString": "AAAAAA"
            },
            "cachedLocations": [ ],
            "isCorrupt": false,
            "locations": [
                {
                    "adminState": "NORMAL",
                    "blockPoolUsed": 7844040235051,
                    "cacheCapacity": 0,
                    "cacheUsed": 0,
                    "capacity": 15997700407296,
                    "dfsUsed": 7844040235051,
                    "hostName": "pg-kvm-hdfs-dn1015",
                    "infoPort": 50075,
                    "infoSecurePort": 0,
                    "ipAddr": "10.4.1.15",
                    "ipcPort": 50020,
                    "lastBlockReportMonotonic": 13750628739,
                    "lastBlockReportTime": 1640440500340,
                    "lastUpdate": 1640444445299,
                    "lastUpdateMonotonic": 13754573698,
                    "name": "10.4.1.15:50010",
                    "networkLocation": "/default-rack",
                    "remaining": 8141550999091,
                    "storageID": "a3a145a9-88c6-4849-a2e2-216d8eef8143",
                    "xceiverCount": 1,
                    "xferPort": 50010
                },
                {
                    "adminState": "NORMAL",
                    "blockPoolUsed": 7798472576268,
                    "cacheCapacity": 0,
                    "cacheUsed": 0,
                    "capacity": 15997700407296,
                    "dfsUsed": 7798472576268,
                    "hostName": "pg-kvm-hdfs-dn1013",
                    "infoPort": 50075,
                    "infoSecurePort": 0,
                    "ipAddr": "10.4.1.13",
                    "ipcPort": 50020,
                    "lastBlockReportMonotonic": 13747610408,
                    "lastBlockReportTime": 1640437482009,
                    "lastUpdate": 1640444444963,
                    "lastUpdateMonotonic": 13754573363,
                    "name": "10.4.1.13:50010",
                    "networkLocation": "/default-rack",
                    "remaining": 8197323507063,
                    "storageID": "fc4a02f7-4a83-44af-8438-a3afea9c691d",
                    "xceiverCount": 2,
                    "xferPort": 50010
                }
            ],
            "startOffset": 268435456,
            "storageTypes": [
                "DISK",
                "DISK"
            ]
        },
        "locatedBlocks": [
            {
                "block": {
                    "blockId": 1122169514,
                    "blockPoolId": "BP-2028409268-10.4.1.16-1583828325109",
                    "generationStamp": 2376930914,
                    "numBytes": 134217728
                },
                "blockToken": {
                    "urlString": "AAAAAA"
                },
                "cachedLocations": [ ],
                "isCorrupt": false,
                "locations": [
                    {
                        "adminState": "NORMAL",
                        "blockPoolUsed": 9015495742346,
                        "cacheCapacity": 0,
                        "cacheUsed": 0,
                        "capacity": 15997700407296,
                        "dfsUsed": 9015495742346,
                        "hostName": "pg-kvm-hdfs-dn1018",
                        "infoPort": 50075,
                        "infoSecurePort": 0,
                        "ipAddr": "10.4.1.18",
                        "ipcPort": 50020,
                        "lastBlockReportMonotonic": 13749704685,
                        "lastBlockReportTime": 1640439576285,
                        "lastUpdate": 1640444445715,
                        "lastUpdateMonotonic": 13754574115,
                        "name": "10.4.1.18:50010",
                        "networkLocation": "/default-rack",
                        "remaining": 6980191326675,
                        "storageID": "9a69bff0-dc92-4bf4-99dd-8a425165bb55",
                        "xceiverCount": 1,
                        "xferPort": 50010
                    },
                    {
                        "adminState": "NORMAL",
                        "blockPoolUsed": 2830936782362,
                        "cacheCapacity": 0,
                        "cacheUsed": 0,
                        "capacity": 15997700407296,
                        "dfsUsed": 2830936782362,
                        "hostName": "pg-kvm-hdfs-dn1005",
                        "infoPort": 50075,
                        "infoSecurePort": 0,
                        "ipAddr": "10.4.1.5",
                        "ipcPort": 50020,
                        "lastBlockReportMonotonic": 13739951773,
                        "lastBlockReportTime": 1640429823373,
                        "lastUpdate": 1640444443755,
                        "lastUpdateMonotonic": 13754572154,
                        "name": "10.4.1.5:50010",
                        "networkLocation": "/default-rack",
                        "remaining": 12368772591616,
                        "storageID": "22ee4f6f-5c5d-4225-9972-d881401829e0",
                        "xceiverCount": 1,
                        "xferPort": 50010
                    }
                ],
                "startOffset": 0,
                "storageTypes": [
                    "DISK",
                    "DISK"
                ]
            },
            {
                "block": {
                    "blockId": 1122185706,
                    "blockPoolId": "BP-2028409268-10.4.1.16-1583828325109",
                    "generationStamp": 2377095530,
                    "numBytes": 134217728
                },
                "blockToken": {
                    "urlString": "AAAAAA"
                },
                "cachedLocations": [ ],
                "isCorrupt": false,
                "locations": [
                    {
                        "adminState": "NORMAL",
                        "blockPoolUsed": 7798472576268,
                        "cacheCapacity": 0,
                        "cacheUsed": 0,
                        "capacity": 15997700407296,
                        "dfsUsed": 7798472576268,
                        "hostName": "pg-kvm-hdfs-dn1013",
                        "infoPort": 50075,
                        "infoSecurePort": 0,
                        "ipAddr": "10.4.1.13",
                        "ipcPort": 50020,
                        "lastBlockReportMonotonic": 13747610408,
                        "lastBlockReportTime": 1640437482009,
                        "lastUpdate": 1640444444963,
                        "lastUpdateMonotonic": 13754573363,
                        "name": "10.4.1.13:50010",
                        "networkLocation": "/default-rack",
                        "remaining": 8197323507063,
                        "storageID": "fc4a02f7-4a83-44af-8438-a3afea9c691d",
                        "xceiverCount": 2,
                        "xferPort": 50010
                    },
                    {
                        "adminState": "NORMAL",
                        "blockPoolUsed": 9015495742346,
                        "cacheCapacity": 0,
                        "cacheUsed": 0,
                        "capacity": 15997700407296,
                        "dfsUsed": 9015495742346,
                        "hostName": "pg-kvm-hdfs-dn1018",
                        "infoPort": 50075,
                        "infoSecurePort": 0,
                        "ipAddr": "10.4.1.18",
                        "ipcPort": 50020,
                        "lastBlockReportMonotonic": 13749704685,
                        "lastBlockReportTime": 1640439576285,
                        "lastUpdate": 1640444445715,
                        "lastUpdateMonotonic": 13754574115,
                        "name": "10.4.1.18:50010",
                        "networkLocation": "/default-rack",
                        "remaining": 6980191326675,
                        "storageID": "9a69bff0-dc92-4bf4-99dd-8a425165bb55",
                        "xceiverCount": 1,
                        "xferPort": 50010
                    }
                ],
                "startOffset": 134217728,
                "storageTypes": [
                    "DISK",
                    "DISK"
                ]
            },
            {
                "block": {
                    "blockId": 1122203888,
                    "blockPoolId": "BP-2028409268-10.4.1.16-1583828325109",
                    "generationStamp": 2377258060,
                    "numBytes": 125220942
                },
                "blockToken": {
                    "urlString": "AAAAAA"
                },
                "cachedLocations": [ ],
                "isCorrupt": false,
                "locations": [
                    {
                        "adminState": "NORMAL",
                        "blockPoolUsed": 7798472576268,
                        "cacheCapacity": 0,
                        "cacheUsed": 0,
                        "capacity": 15997700407296,
                        "dfsUsed": 7798472576268,
                        "hostName": "pg-kvm-hdfs-dn1013",
                        "infoPort": 50075,
                        "infoSecurePort": 0,
                        "ipAddr": "10.4.1.13",
                        "ipcPort": 50020,
                        "lastBlockReportMonotonic": 13747610408,
                        "lastBlockReportTime": 1640437482009,
                        "lastUpdate": 1640444444963,
                        "lastUpdateMonotonic": 13754573363,
                        "name": "10.4.1.13:50010",
                        "networkLocation": "/default-rack",
                        "remaining": 8197323507063,
                        "storageID": "fc4a02f7-4a83-44af-8438-a3afea9c691d",
                        "xceiverCount": 2,
                        "xferPort": 50010
                    },
                    {
                        "adminState": "NORMAL",
                        "blockPoolUsed": 7844040235051,
                        "cacheCapacity": 0,
                        "cacheUsed": 0,
                        "capacity": 15997700407296,
                        "dfsUsed": 7844040235051,
                        "hostName": "pg-kvm-hdfs-dn1015",
                        "infoPort": 50075,
                        "infoSecurePort": 0,
                        "ipAddr": "10.4.1.15",
                        "ipcPort": 50020,
                        "lastBlockReportMonotonic": 13750628739,
                        "lastBlockReportTime": 1640440500340,
                        "lastUpdate": 1640444445299,
                        "lastUpdateMonotonic": 13754573698,
                        "name": "10.4.1.15:50010",
                        "networkLocation": "/default-rack",
                        "remaining": 8141550999091,
                        "storageID": "a3a145a9-88c6-4849-a2e2-216d8eef8143",
                        "xceiverCount": 1,
                        "xferPort": 50010
                    }
                ],
                "startOffset": 268435456,
                "storageTypes": [
                    "DISK",
                    "DISK"
                ]
            }
        ]
    }
}
*/
